=== rbccps-iisc/iudx-schemas/base_schemas/v0.0.1/iudx_item_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "describes": "Base schema of catalog entries",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "describes": "Unique identifier of the data resource within this domain"
    },
    "itemDescription": {
      "type": "string",
      "describes": "Text description of this item."
    },
    "refDataModel": {
      "type": "string",
      "format": "uri",
      "describes": "Reference to the data model for this catalog item. It is assumed that the referred to data-model(schema) has already been uploaded into the catalog OR stored in a pre-defined repository. The catalogue item comprises of fields from the refDataModel along with the refBaseSchema."
    },
    "refBaseSchema": {
      "type": "string",
      "format": "uri",
      "describes": "Reference to the IUDX base schema for this catalog item. It is assumed that the referred base schema has already been uploaded into the catalog OR stored in a pre-defined repository. The catalogue item comprises of fields from the refDataModel along with the refBaseSchema."
    },
    "refBaseSchemaRelease": {
      "type": "string",
      "describes": "Release number/label associated with the IUDX base schema (refBaseSchema) used for this item."
    },
    "provider": {
      "$ref": "https://raw.githubusercontent.com/rbccps-iisc/iudx-schemas/master/base_schemas/v0.0.1/iudx_base_def.json#/definitions/refToProviderItemSchema"
    },
    "tags": {
      "$ref": "https://raw.githubusercontent.com/rbccps-iisc/iudx-schemas/master/base_schemas/v0.0.1/iudx_base_def.json#/definitions/tagsSchema"
    },
    "__itemStatus": {
      "$ref": "https://raw.githubusercontent.com/rbccps-iisc/iudx-schemas/master/base_schemas/v0.0.1/iudx_base_def.json#/definitions/itemStatusSchema"
    },
    "__itemType": {
      "$ref": "https://raw.githubusercontent.com/rbccps-iisc/iudx-schemas/master/base_schemas/v0.0.1/iudx_base_def.json#/definitions/itemTypeSchema"
    },
    "__createdAt": {
       "type": "string",
       "format": "date-time",
       "describes": "Date of creation of this entry in the catalogue."
    },
    "__updatedAt": {
       "type": "string",
       "format": "date-time",
       "describes": "Last update date/time for this entry in the catalogue."
    },
    "__deprecatedAt": {
       "type": "string",
       "format": "date-time",
       "describes": "Date/time when this entry was deprecated (status set to deprecated)."
    },
    "__catalogueInstanceId": {
       "type": "string",
       "describes": "Registered Id of the IUDX-catalouge instance to which this item belongs."
    }
  },
  "additionalProperties": {
    "type": ["number", "integer", "null", "string", "object", "boolean", "array"]
  },
  "required": ["id", "refDataModel", "refBaseSchema", "provider", "tags"]
}

=== rbccps-iisc/iudx-schemas/base_schemas/v0.0.1/test/test_iudx_item_schema.json
{
  "id": "8898kwiorit9490494",
  "itemDescription": "Description of a resource",
  "refDataModel": "not_required.json",
  "refBaseSchema": "https://raw.githubusercontent.com/rbccps-iisc/iudx-schemas/master/base_schemas/v0.0.1/iudx_item_schema.json",
  "refBaseSchemaRelease": "v0.0.1",
  "provider": {
    "refItemName": "PSCDCL",
    "refItemId": "al74709345984395007094"
  },
  "tags": [ "air", "pollution", "SO2", "CO2", "CO", "NO"],
  "__itemStatus": "active",
  "__itemType": "resource-item",
  "__createdAt": "2019-02-20T10:30:06.093121",
  "__catalogueInstanceId": "2019-02-20T10:30:06.093121",
  "__updatedAt": "2019-02-20T10:30:06.093121"
}

=== rbccps-iisc/iudx-schemas/base_schemas/v0.0.0/test/test_iudx_item_schema.json
{
  "id": "8898kwiorit9490494",
  "itemDescription": "Description of a resource",
  "refDataModel": "not_required.json",
  "refBaseSchema": "https://raw.githubusercontent.com/rbccps-iisc/iudx-schemas/master/base_schemas/v0.0.0/iudx_item_schema.json",
  "refBaseSchemaRelease": "v0.0.0",
  "provider": {
    "entityId": "PSCDCL",
    "entityIdentityType": "X509",
    "entityIdentityProviderURL" : "https://ca.iudx.org.in",
    "entityURL" : "https://punesmartcity.in/",
    "entityContactPhone": ""
  },
  "tags": [ "air", "pollution", "SO2", "CO2", "CO", "NO"],
  "__itemStatus": "active",
  "__itemType": "item",
  "__createdAt": "2019-02-20T10:30:06.093121",
  "__catalogueInstanceId": "2019-02-20T10:30:06.093121",
  "__updatedAt": "2019-02-20T10:30:06.093121"
}
